spring.application.name=GUI-Fenix
spring.main.web-application-type=none
application.title=From Minor to Major: Solfeggio Basics

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
driverClassName=org.sqlite.JDBC
url=jdbc:sqlite:data/index_of_projects.db

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=false